dist: trusty
language: node_js

# User container based travis infrastructure which allows caching
# features for open source projects.
sudo: false
cache:
  directories:
    - node_modules

addons:
  chrome: stable
